config/routes.rb
require 'subdomain'
TipHive::Application.routes.draw do

  resources :action_logs

  post '/tiphive_settings' => 'tiphive_settings#index'
  get '/switch_group' => 'tiphive_settings#switch_domain_setting'
  resources :tiphive_settings do 
    collection do
      post :get_domain
      get :hives
    end
  end

  get 'sidebar/tips'
  get 'sidebar/questions'
  get 'sidebar/my_hives'
  get 'sidebar/my_groups'
  get 'sidebar/my_friends'

  constraints(Subdomain) do
    get '/' => 'domains#home'
  end

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        resources :users
        resources :comments
        resources :groups do
          resources :tips
        end
        resources :hives do
          resources :tips
        end
        resources :pockets do
          resources :tips
        end
        resources :tips
        resources :questions

        post '/sign_in' => 'sessions#create'
        delete '/sign_out' => 'sessions#destroy'
        post '/sign_up' => 'registrations#create'
        get '/me' => 'users#me'
        get '/friends' => 'users#my_friends'

        get '/search' => 'search#index'
        get '/search_mentions' => 'search#mentions'
        get '/search_users' => 'search#users'
        get '/search_groups' => 'search#groups'
        get '/search_invitable_groups' => 'search#invitable_groups'
        get '/search_users_and_groups' => 'search#users_and_groups'
        get '/search_hives' => 'search#hives'
        get '/search_pockets' => 'search#pockets'
        get '/search_tips' => 'search#tips'
        get '/search_connections' => 'search#connections'
        get '/user_following_friends' => 'search#user_following_friends'
        get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
        get '/user_following_groups' => 'search#user_following_groups'
        get '/user_following_hives' => 'search#user_following_hives'
        get '/user_following_pockets' => 'search#user_following_pockets'
        get '/user_following_tips' => 'search#user_following_tips'
        get '/share_type_permission' => 'search#share_type_permission'
        get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
        post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
        post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
        # use_link_thumbnailer
        resources :pictures
        match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
        match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]
        match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
        resources :comments

        resources :files

        get '/validates_invitation_token' => 'invitation_requests#validates_invitation_token', as: :validates_invitation_token
        get '/invitation_request_from_token' => 'invitation_requests#invitation_request_from_token', as: :invitation_request_from_token
        get '/invitation_requests/:id/accept' => 'invitation_requests#accept', as: :accept_invitation_request
        get '/menu_invitation_requests' => 'invitation_requests#menu_invitation_requests'
        resources :invitation_requests

        resources :groups do
          resources :hives
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :request_invite
            post :request_invite
            get :members
            get :no_access
          end
        end
        get '/groups/:id/members/:initial' => 'groups#members', as: :group_members_by_initial
        get '/domains/:id/members/:initial' => 'domains#members', as: :domain_members_by_initial

        get '/my_groups' => 'groups#my_groups'
        get '/menu_groups' => 'groups#menu_groups'

        resources :tip_links do
          collection do
            get '/fetch' => 'tip_links#fetch'
          end
        end
        resources :tips do
          post '/like' => 'tips#like'
          post '/unlike' => 'tips#unlike'
          get '/get_tip' => 'tips#get_tip'
          post '/flag' => 'tips#flag'
          post '/update_tip_location' => 'tips#update_tip_location'
          collection do
            post '/business' => 'tips#business'
          end
          member do
            get :share
            get :hives_and_pockets
          end
        end

        resources :questions do
          post '/like' => 'questions#like'
          post '/unlike' => 'questions#unlike'
          post '/flag' => 'questions#flag'
          member do
            get :add_existing_tip
            get :add_comment
            get :hives_and_pockets
            get :shared_objects
          end
        end


        resources :pockets do
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :object_setting_model
            post :object_setting
            put :object_setting
          end
        end
        get '/my_pockets' => 'pockets#my_pockets'

        resources :hives do
          resources :pockets
          resources :questions
          get '/my_pockets' => 'pockets#my_pockets'
          member do
            get :leave
            get :join
            get :share
            get :friends
            post :object_setting
            put :object_setting
          end
          collection do
            get :following_pockets
          end
        end
        get '/my_hives' => 'hives#my_hives'
        get '/menu_hives' => 'hives#menu_hives'

        get '/tips' => 'tips#index', as: :user_root

        resources :users do
          resources :hives
          resources :questions
          member do
            get :friends
          end
        end
        resources :domains do
          member do
            get :members
            get :billing
            get :share
          end
        end

        post '/upload_image' => 'pictures#upload_image'
        post '/upload_background_image' => 'pictures#upload_background_image'
        post '/upload_avatar_image' => 'pictures#upload_avatar_image'
        post '/upload_avatar' => 'users#upload_avatar'
        get '/select_avatar' => 'users#select_avatar'
        get '/email_notifications' => 'users#email_notifications'
        post '/email_notifications' => 'users#email_notifications'
        post '/add_as_friend/:user_id' => 'users#add_as_friend', as: :add_as_friend
        post '/add_as_friends' => 'users#add_as_friends', as: :add_as_friends
        post '/unfriend/:user_id' => 'users#unfriend', as: :unfriend
        get '/status_with/:user_id' => 'users#status_with', as: :status_with

        get '/users/:id' => 'users#show', as: :user_profile
        get '/my_friends/:initial' => 'users#my_friends', as: :my_friends_by_initial
        get '/my_friends' => 'users#my_friends'
        get '/add_friends' => 'users#add_friends'
        post '/add_friends' => 'users#add_friends'
        get '/count_element' => 'users#user_count_element'

        post '/connect_following_objects' => 'home#connect_following_objects', as: :connect_following_objects
        post '/disconnect_following_objects' => 'home#disconnect_following_objects', as: :disconnect_following_objects
        post '/update_background_image_position' => 'home#update_background_image_position'
      end

      get '*unmatched_route', to: 'application#raise_not_found!'
      post '*unmatched_route', to: 'application#raise_not_found!'
      put '*unmatched_route', to: 'application#raise_not_found!'
      delete '*unmatched_route', to: 'application#raise_not_found!'
    end
  end

  get '/search' => 'search#index'
  get '/search_mentions' => 'search#mentions'
  get '/search_users' => 'search#users'
  get '/search_groups' => 'search#groups'
  get '/search_invitable_groups' => 'search#invitable_groups'
  get '/search_users_and_groups' => 'search#users_and_groups'
  get '/search_hives' => 'search#hives'
  get '/search_pockets' => 'search#pockets'
  get '/search_tips' => 'search#tips'
  get '/search_connections' => 'search#connections'
  get '/search_social_friends' =>  'search#social_friends'
  post '/search_social_friends' =>  'search#social_friends'
  get '/user_following_friends' => 'search#user_following_friends'
  get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
  get '/user_following_groups' => 'search#user_following_groups'
  get '/user_following_hives' => 'search#user_following_hives'
  get '/user_following_pockets' => 'search#user_following_pockets'
  get '/user_following_tips' => 'search#user_following_tips'
  get '/share_type_permission' => 'search#share_type_permission'
  get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
  post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
  post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
  # use_link_thumbnailer
  resources :pictures do
    collection do
      post 'tag'
    end
    member do
      post 'remove_tag', :as => :remove_tag
    end
  end
  match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
  match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]

  resources :files
  match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
  resources :comments

  get '/menu_friend_invitations' => 'friend_invitations#menu_friend_invitations'
  resources :friend_invitations

app/controllers/api/v1/search_controller.rb
class Api::V1::SearchController < SearchController
  include TipHiveHelper
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include TipHiveHelper

  # GET /search
  # GET /search.json
  def index
    params[:type] = 'Tip' if params[:type].blank?

    search_classes = [User, Group, Hive, Tip, Question]
    search_classes = [Tip] if params[:type] == 'Tip'
    search_classes = [Hive] if params[:type] == 'Hive'
    search_classes = [User] if params[:type] == 'User'
    search_classes = [Group] if params[:type] == 'Group'
    search_classes = [Question] if params[:type] == 'Question'

    search_objects_and_render(search_classes, params[:q])
  end

  # GET /search_users
  # GET /search_users.json
  def users
    search_objects_and_render([User], params[:q])
  end

  # GET /search_groups
  # GET /search_groups.json
  def groups
    search_objects_and_render([Group], params[:q])
  end

  # TODO: may need to refactor
  def invitable_groups
    params[:type] = 'Group'

    @search = Group.solr_search do
      fulltext(params[:q]) do
        if params[:fields].present?
          search_fields = params[:fields].split(',')
          search_fields.each do |search_field|
            fields(search_field)
          end
        end
        fields params[:field] if params[:field].present?
      end if params[:q].present?

      with :group_type, params[:group_type] if %w(university enterprise event).include?(params[:group_type])

      current_page = params[:page].to_i > 0 ? params[:page].to_i : 1
      per_page     = params[:per].to_i > 0 ? params[:per].to_i : 6
      paginate(page: current_page, per_page: per_page)
    end

    @results = @search.results

    render template: 'search/index'
  end

  # GET /search_users_and_groups
  # GET /search_users_and_groups.json
  def users_and_groups
    search_objects_and_render([User, Group], params[:q])
  end

  # GET /search_hives
  # GET /search_hives.json
  def hives
    search_objects_and_render([Hive], params[:q])
  end

  # GET /search_pockets
  # GET /search_pockets.json
  def pockets
    if params[:hives].include?('null')
      search_objects_and_render([Pocket], params[:q])
    else
      hives          = params[:hives][0].split(',')
      selected_hives = collect_items(items_list: hives)
      @results       = Hive.search_pocket(selected_hives, params[:q])
      render template: 'search/index'
    end
  end

  # GET /search_tips
  # GET /search_tips.json
  def tips
    search_objects_and_render([Tip], params[:q])
  end

  # GET /user_following_friends_and_groups
  # GET /user_following_friends_and_groups.json
  def user_following_friends_and_groups
    params[:followable_types] = 'User,Group'
    params[:followable_types] = params[:only] if params[:only].present?
    user_following_connections_and_render(params)
  end

  # GET /user_following_friends
  # GET /user_following_friends.json
  def user_following_friends
    params[:followable_type] = 'User'
    user_following_connections_and_render(params)
  end

  # GET /user_following_groups
  # GET /user_following_groups.json
  def user_following_groups
    params[:followable_type] = 'Group'
    user_following_connections_and_render(params)
  end

  # GET /user_following_hives
  # GET /user_following_hives.json
  def user_following_hives
    params[:followable_type] = 'Hive'
    user_following_connections_and_render(params)
  end

  # GET /user_following_pockets
  # GET /user_following_pockets.json
  def user_following_pockets
    params[:followable_type] = 'Pocket'
    user_following_connections_and_render(params)
  end

  # GET /user_following_tips
  # GET /user_following_tips.json
  def user_following_tips
    params[:followable_type] = 'Tip'
    user_following_connections_and_render(params)
  end

  # GET /search_connections
  # GET /search_connections.json
  def user_following_connections_and_render(params)
    @results = []
    @results += user_following_connections(params)
    @results += search_objects([User], params[:q]).results - [current_user] if params[:q].present?

    if params[:followable_types] == 'User,Group' || params[:followable_type] == 'User'
      @results += FriendList.all if params[:only].blank? && params[:type] != 'without_friend_lists'
    end

    render template: 'search/connections'
  end

  def mentions
    params[:field] = :username
    @search        = search_objects([User], params[:q])
    @results       = @search.results

    respond_to do |format|
      format.json { render json: @results.map(&:username).reject(&:blank?) }
    end
  end

  # GET /share_type_permission
  # GET /share_type_permission.json
  def share_type_permission
    @result        = []
    hives          = params[:hives][0].split(',')
    selected_hives = collect_items(items_list: hives)
    @result        = Hive.get_hive_sharing_permission(selected_hives, current_user) if current_user
    render template: 'search/share_types'
  end

  # GET /hives_following_users_and_groups
  # GET /hives_following_users_and_groups.js
  # if hive permission is selected friends/groups
  def hives_following_users_and_groups
    @object = Tip.new if params[:object].include? ('Tip')
    @object = Question.new if params[:object].include? ('Question')
    @object = Pocket.new if params[:object].include? ('Pocket')
    @object = collect_items(items_list: params[:object]).first if params[:edit]

    hives          = params[:hives][0].split(',')
    selected_hives = collect_items(items_list: hives)
    @selected_friends_and_groups = []
    selected_hives.each do |hive|
      shared_objects = hive.get_shared_objects(current_user)
      next unless shared_objects
      @selected_friends_and_groups << (shared_objects - [current_user])
    end
    @selected_friends_and_groups = @selected_friends_and_groups.flatten

    if params[:edit].present?
      # Disconnect existing followers
      @tips_followers = []
      @tips_followers << @object.users
      @tips_followers << @object.groups
      @tips_followers << @object.friend_lists

      @tips_followers.flatten.each do |item|
        item.stop_following @object
        # when item is FriendList class object then update #{@object} attributes  
        item.update_object_sharing_status_false(@object) if item.class.name == 'FriendList'
      end

      # Connected new followers
      if @object.is_private == false
        @selected_friends_and_groups.each do |item|
          item.follow @object
          # when item is FriendList class object then update #{@object} attributes 
          item.update_object_sharing_status_true(@object) if item.class.name == 'FriendList'
        end
      end
    end
  end

  def social_friends
    if params[:q] && params[:type]
      if params[:type] == 'facebook'
        @results = current_user.social_friends.where('name like ? AND provider = ?', "%#{params[:q]}%", params[:type])
      elsif params[:type] == 'google_oauth2'
        @results = current_user.social_friends.where('email like ? AND provider = ?', "%#{params[:q]}%", params[:type])
      end
      render template: 'search/social_friends'
    else
      @contacts = current_user.social_friends.where(uid: params[:uid]) if params[:uid]
      @contacts = current_user.social_friends.where(email: params[:email]) if params[:email]
      respond_to do |format|
        format.js
      end
    end
  end

  private
  def search_objects_and_render(object_classes, query = '')
    @search  = search_objects(object_classes, query)
    @results = @search.results
    if api?
      render template: 'api/v1/search/index'
    else
      render template: 'search/index'
    end
  end
end

app/views/search/_friends_and_groups_select_for_sharing.html.haml
- if local_assigns[:selected_friends_and_groups]
  - values = selected_friends_and_groups.map{ |h| h.kind_id }
  - options =  options_from_collection_for_select(selected_friends_and_groups, :kind_id, :name, values)

= select_tag 'select_friends_and_groups[]', options,
             placeholder: local_assigns[:placeholder] ? local_assigns[:placeholder] : 'Type to search or select friends and groups',
             id: 'select_friends_and_groups',
             class: 'form-control',
             multiple: 'multiple'

= render 'search/friends_and_groups_select_for_sharing_script', object: object, only: local_assigns[:only]

app/views/search/_friends_and_groups_select_for_sharing_script.html.erb
<script>
  $(document).ready(function(e){
    var select_friends, $select_friends;
    $select_friends = $('select#select_friends_and_groups').selectize({
      valueField: 'kind_id',
      labelField: 'name',
      searchField: 'name',
      sortField: 'kind_id',
      optgroups: [
        {value: 'FriendList', label: 'Friend List'},
        {value: 'Group', label: 'Groups'},
        {value: 'Friend', label: 'Friends'},
        {value: 'NotFriend', label: 'Not Friends'}
      ],
      lockOptgroupOrder: true,
      persist: true,
      plugins: ['remove_button'],
      preload: 'focus',
      render: {
        item: function(item, escape) {
          return '<div class="item"><span class="label label-info">' + escape(item['kind_id'].split('-')[0]) + '</span>' + escape(item['name']) + '</div>';
        },
        option: function(item, escape) {
          return '<div class="option"><span class="label label-default">' + escape(item['kind_id'].split('-')[0]) + '</span>' + escape(item['name']) + '</div>';
        }
      },
      load: function(query, callback) {
        $.ajax({
          url: '/user_following_friends_and_groups.json',
          data: { q: query, only: '<%= local_assigns[:only] %>' },
          type: 'GET',
          dataType: 'json',
          error: function() {
            callback();
          },
          success: function(res) {
            callback(res);
          }
        });
      },
      onLoad: function (data) {
        this.refreshOptions(false);
      },
      onItemAdd: function(value, $item) {
        $.ajax({
          url: '<%= connect_sharing_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', items_list: [value] }
        });

        $.ajax({
          url: '<%= connect_following_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'following', items_list: [value] }
        });

        this.refreshOptions(false);
      },
      onItemRemove: function(value) {
        $.ajax({
          url: '<%= disconnect_sharing_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', items_list: [value] }
        });
        $.ajax({
          url: '<%= disconnect_following_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'following', items_list: [value] }
        });

        this.refreshOptions(false);
      }
    });

    // Only for new pocket creation, where sharing setting load first after that we are showing save button
    if ($select_friends && $select_friends.length) {
      select_friends = $select_friends[0].selectize;
      var $saveDisable = $('.save-disable');

      if (select_friends.items.length < 0) {
        $saveDisable.show();
      }
      else {
        $saveDisable.show();
      }
    }
  });
</script>

app/views/search/_hives_and_pockets_select_script_for_tips.html.erb
<script>
  $(document).ready(function(e){
    var xhr;
    var select_hives, $select_hives;
    var select_pockets, $select_pockets;
    var selected_pocket;
    var selected_groups;
    var $selected_group = $("#select_friends_and_groups").selectize();
    var selectize = $selected_group[0].selectize;

    if ($selected_group && $selected_group.length) {
      selectize  = $selected_group[0].selectize;
      var group = selectize.items;
      var str = group[0];
      var patt = new RegExp("Group");
      var res = patt.test(str);
      if (res) {
        selected_groups = group;
      }
      else
      {
        selected_groups = [];
      }
    }

    var action = '<%= params[:action] %>';
    $select_hives = $('select#<%= object.class.name.downcase %>_hives').selectize({
      valueField: 'kind_id',
      labelField: 'name',
      searchField: 'name',
      //sortField: 'name',
      persist: true,
      plugins: ['remove_button'],
      render: {
        item: function(item, escape) {
          return '<div class="item"><span class="label label-info">Hive</span>' + escape(item['name']) + '</div>';
        },
        option: function(item, escape) {
          return '<div class="option">' + escape(item['name']) + '</div>';
        },
        option_create: function(data, escape) {
          return '<div class="create">Add new Hive: <strong>' + escape(data.input) + '</strong>&hellip;</div>';
        }
      },
      create: function(input) {
        if (input.length > 2) {
          var hive = { name: input, kind_id: null };
          $.ajax({
            url: '<%= hives_path %>',
            type: 'POST',
            async: false,
            dataType: 'json',
            data: { hive: { title: input}, select_friends_and_groups: selected_groups }
          }).done(function (data) {
            //JSON response: views/api/v1/hives/show.json
            hive.kind_id = 'Hive-' + data.response.id;
          });
          return hive;
        } else {
          alert('Hive name too short.');
          return false;
        }

      },
      onItemAdd: function(value, $item) {
        $.ajax({
          url: '<%= connect_following_objects_path(format: :js) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'follower', items_list: [value] }
        });

        if (!value.length || !$select_pockets.length) return;
        // this condition only for new action
        if (action != 'edit' && action != 'update') {
          select_pockets.disable();
          select_pockets.clearOptions();
        }
        select_pockets.load(function(callback) {
          xhr && xhr.abort();
          xhr = $.ajax({
            url: '<%= following_pockets_hives_path(format: :json) %>',
            beforeSend: function(xhr, settings) {
              var selHives = getSelectedHives();
              settings.url += "?hives[]="+ selHives.items;
            },
            success: function(results) {
              select_pockets.enable();
              callback(results);
            },
            error: function() {
              callback();
            }
          })
        });

        // when select hive, set hive default permission to tip
        xhr = fetchHivePermissions();
      },
      onItemRemove: function(value) {
        $.ajax({
          url: '<%= disconnect_following_objects_path(format: :js) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'follower', items_list: [value] }
        });

        if (!value.length || !$select_pockets.length) return;
        // this condition only for new action
        if (action != 'edit' && action != 'update') {
          select_pockets.disable();
          select_pockets.clearOptions();
        }
        select_pockets.load(function(callback) {
          xhr && xhr.abort();
          xhr = $.ajax({
            url: '<%= following_pockets_hives_path(format: :json) %>',
            beforeSend: function(xhr, settings) {
              var selHives = getSelectedHives();
              settings.url += "?hives[]="+ selHives.items;
            },
            success: function(results) {
              select_pockets.enable();
              callback(results);
            },
            error: function() {
              callback();
            }
          })
        });

        // when remove hive, set hive default permission to tip
        xhr = fetchHivePermissions();
      }

    });

    $select_pockets = $('select#<%= object.class.name.downcase %>_pockets').selectize({
      optgroupField: 'title',
      optgroupLabelField: 'title',
      valueField: 'kind_id',
      labelField: 'name',
      searchField: 'name',
      sortField: 'name',
      persist: true,
      plugins: ['remove_button'],
      render: {
        item: function(item, escape) {
          return '<div class="item"><span class="label label-info">Pocket</span>' + escape(item['name']) + '</div>';
        },
        option: function(item, escape) {
          return '<div class="option">' + escape(item['name']) + '</div>';
        },
        optgroup_header: function(item, escape) {
          return '<div class="optgroup-header">' + escape(item['title']) + '</div>';
        },
        option_create: function(data, escape) {
          return '<div class="create">Add new Pocket: <strong>' + escape(data.input) + '</strong>&hellip;</div>';
        }
      },
      create: function(input) {
        if (input.length > 2) {
          var pocket = { name: input, kind_id: null };
          $.ajax({
            url: '<%= pockets_path %>',
            type: 'POST',
            async: false,
            dataType: 'json',
            data: { pocket: { title: input }, 'hives[]': $('select#<%= object.class.name.downcase %>_hives').val() }
          }).done(function (data) {
            //JSON response: views/api/v1/pockets/show.json
            pocket.kind_id = 'Pocket-' + data.response.id;
          });
          return pocket;
        } else {
          alert('Pocket name too short.');
          return false;
        }
      },
      onItemAdd: function(value, $item) {
        $.ajax({
          url: '<%= connect_following_objects_path(format: :js) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'follower', items_list: [value] }
        });
      },
      onItemRemove: function(value) {
        $.ajax({
          url: '<%= disconnect_following_objects_path(format: :js) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'follower', items_list: [value] }
        });
      }
    });

    if ($select_pockets && $select_pockets.length) {
      select_pockets  = $select_pockets[0].selectize;
      selected_pocket = select_pockets.items;
    }

    if ($select_hives && $select_hives.length) {
      select_hives = $select_hives[0].selectize;
      // show only selected hive pockets
      if ((select_hives.items.length > 0) && (action != 'edit' && action != 'update')) {
        if (!selected_pocket.length > 0) {
          select_pockets.disable();
          select_pockets.clearOptions();
        }
        select_pockets.load(function(callback) {
          xhr && xhr.abort();
          xhr = $.ajax({
            url: '<%= following_pockets_hives_path(format: :json) %>',
            beforeSend: function(xhr, settings) {
              var selHives = getSelectedHives();
              settings.url += "?hives[]="+ selHives.items;
            },
            success: function(results) {
              select_pockets.enable();
              callback(results);
              select_pockets.addItem(selected_pocket);
            },
            error: function() {
              callback();
            }
          });
        });

        // set default permission to tip, If hive already selected
        xhr = fetchHivePermissions();
      }
    }

    function fetchHivePermissions() {
      return $.ajax({
        url: '<%= share_type_permission_path(format: :json) %>',
        beforeSend: function(xhr, settings) {
          var selHives = getSelectedHives();
          settings.url += "?hives[]="+ selHives.items;
        },
        success: function(res) {
          if (res[0]) {
            setShareTab(res[0].name);
          }
        },
        error: function() {

        }
      });
    }

    // get selected hives
    function getSelectedHives() {
      if ($select_hives && $select_hives.length) {
        select_hives = $select_hives[0].selectize;
      }
      return select_hives;
    }

    // set radio button type based on permission type
    function setShareTab(name){
      if (name == 'select_friends') {
        $('input[id="<%= object.class.name.downcase %>_is_private"]').bootstrapSwitch('state', false, false);
        $('#friends_and_group_select_box').removeClass('hide');

        xhr = $.ajax({
          url: '<%= hives_following_users_and_groups_path(format: :js) %>',
          beforeSend: function(xhr, settings) {
            var selHives = getSelectedHives();
            var object = "<%= object.new_record? ? object.class.name : object.kind_id %>";
            var inline_object = "<%= inline_object.present? ? inline_object : '' %>";

            settings.url += "?hives[]="+ selHives.items;

            if ((object == 'Tip' || object == 'Question') && inline_object == 'inline_form') {
              settings.url += "&object[]=" + object + "&inline_object=" + inline_object ;
            } else if (object == 'Tip' || object == 'Question') {
              settings.url += "&object[]=" + object ;
            } else {
              settings.url += "&object[]=" + object + "&edit=" + 'edit';
            }
          },
          success: function(results) {

          },
          error: function() {

          }
        });
      }

      if (name == 'private') {
        $('input[id="<%= object.class.name.downcase %>_is_private"]').bootstrapSwitch('state', true, true);

        // If share seting of hive is private then question notify friends field should be private
        $('#notify_friends').bootstrapSwitch('state', false, false);

        // If share setting of hive is private then share? field should be private
        $('#friends_and_group_select_box').addClass('hide')
      }
    }
  });
</script>