config/routes.rb
require 'subdomain'
TipHive::Application.routes.draw do

  resources :action_logs

  post '/tiphive_settings' => 'tiphive_settings#index'
  get '/switch_group' => 'tiphive_settings#switch_domain_setting'
  resources :tiphive_settings do 
    collection do
      post :get_domain
      get :hives
    end
  end

  get 'sidebar/tips'
  get 'sidebar/questions'
  get 'sidebar/my_hives'
  get 'sidebar/my_groups'
  get 'sidebar/my_friends'

  constraints(Subdomain) do
    get '/' => 'domains#home'
  end

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        resources :users
        resources :comments
        resources :groups do
          resources :tips
        end
        resources :hives do
          resources :tips
        end
        resources :pockets do
          resources :tips
        end
        resources :tips
        resources :questions

        post '/sign_in' => 'sessions#create'
        delete '/sign_out' => 'sessions#destroy'
        post '/sign_up' => 'registrations#create'
        get '/me' => 'users#me'
        get '/friends' => 'users#my_friends'

        get '/search' => 'search#index'
        get '/search_mentions' => 'search#mentions'
        get '/search_users' => 'search#users'
        get '/search_groups' => 'search#groups'
        get '/search_invitable_groups' => 'search#invitable_groups'
        get '/search_users_and_groups' => 'search#users_and_groups'
        get '/search_hives' => 'search#hives'
        get '/search_pockets' => 'search#pockets'
        get '/search_tips' => 'search#tips'
        get '/search_connections' => 'search#connections'
        get '/user_following_friends' => 'search#user_following_friends'
        get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
        get '/user_following_groups' => 'search#user_following_groups'
        get '/user_following_hives' => 'search#user_following_hives'
        get '/user_following_pockets' => 'search#user_following_pockets'
        get '/user_following_tips' => 'search#user_following_tips'
        get '/share_type_permission' => 'search#share_type_permission'
        get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
        post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
        post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
        # use_link_thumbnailer
        resources :pictures
        match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
        match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]
        match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
        resources :comments

        resources :files

        get '/validates_invitation_token' => 'invitation_requests#validates_invitation_token', as: :validates_invitation_token
        get '/invitation_request_from_token' => 'invitation_requests#invitation_request_from_token', as: :invitation_request_from_token
        get '/invitation_requests/:id/accept' => 'invitation_requests#accept', as: :accept_invitation_request
        get '/menu_invitation_requests' => 'invitation_requests#menu_invitation_requests'
        resources :invitation_requests

        resources :groups do
          resources :hives
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :request_invite
            post :request_invite
            get :members
            get :no_access
          end
        end
        get '/groups/:id/members/:initial' => 'groups#members', as: :group_members_by_initial
        get '/domains/:id/members/:initial' => 'domains#members', as: :domain_members_by_initial

        get '/my_groups' => 'groups#my_groups'
        get '/menu_groups' => 'groups#menu_groups'

        resources :tip_links do
          collection do
            get '/fetch' => 'tip_links#fetch'
          end
        end
        resources :tips do
          post '/like' => 'tips#like'
          post '/unlike' => 'tips#unlike'
          get '/get_tip' => 'tips#get_tip'
          post '/flag' => 'tips#flag'
          post '/update_tip_location' => 'tips#update_tip_location'
          collection do
            post '/business' => 'tips#business'
          end
          member do
            get :share
            get :hives_and_pockets
          end
        end

        resources :questions do
          post '/like' => 'questions#like'
          post '/unlike' => 'questions#unlike'
          post '/flag' => 'questions#flag'
          member do
            get :add_existing_tip
            get :add_comment
            get :hives_and_pockets
            get :shared_objects
          end
        end


        resources :pockets do
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :object_setting_model
            post :object_setting
            put :object_setting
          end
        end
        get '/my_pockets' => 'pockets#my_pockets'

        resources :hives do
          resources :pockets
          resources :questions
          get '/my_pockets' => 'pockets#my_pockets'
          member do
            get :leave
            get :join
            get :share
            get :friends
            post :object_setting
            put :object_setting
          end
          collection do
            get :following_pockets
          end
        end
        get '/my_hives' => 'hives#my_hives'
        get '/menu_hives' => 'hives#menu_hives'

        get '/tips' => 'tips#index', as: :user_root

        resources :users do
          resources :hives
          resources :questions
          member do
            get :friends
          end
        end
        resources :domains do
          member do
            get :members
            get :billing
            get :share
          end
        end

        post '/upload_image' => 'pictures#upload_image'
        post '/upload_background_image' => 'pictures#upload_background_image'
        post '/upload_avatar_image' => 'pictures#upload_avatar_image'
        post '/upload_avatar' => 'users#upload_avatar'
        get '/select_avatar' => 'users#select_avatar'
        get '/email_notifications' => 'users#email_notifications'
        post '/email_notifications' => 'users#email_notifications'
        post '/add_as_friend/:user_id' => 'users#add_as_friend', as: :add_as_friend
        post '/add_as_friends' => 'users#add_as_friends', as: :add_as_friends
        post '/unfriend/:user_id' => 'users#unfriend', as: :unfriend
        get '/status_with/:user_id' => 'users#status_with', as: :status_with

        get '/users/:id' => 'users#show', as: :user_profile
        get '/my_friends/:initial' => 'users#my_friends', as: :my_friends_by_initial
        get '/my_friends' => 'users#my_friends'
        get '/add_friends' => 'users#add_friends'
        post '/add_friends' => 'users#add_friends'
        get '/count_element' => 'users#user_count_element'

        post '/connect_following_objects' => 'home#connect_following_objects', as: :connect_following_objects
        post '/disconnect_following_objects' => 'home#disconnect_following_objects', as: :disconnect_following_objects
        post '/update_background_image_position' => 'home#update_background_image_position'
      end

      get '*unmatched_route', to: 'application#raise_not_found!'
      post '*unmatched_route', to: 'application#raise_not_found!'
      put '*unmatched_route', to: 'application#raise_not_found!'
      delete '*unmatched_route', to: 'application#raise_not_found!'
    end
  end

  get '/search' => 'search#index'
  get '/search_mentions' => 'search#mentions'
  get '/search_users' => 'search#users'
  get '/search_groups' => 'search#groups'
  get '/search_invitable_groups' => 'search#invitable_groups'
  get '/search_users_and_groups' => 'search#users_and_groups'
  get '/search_hives' => 'search#hives'
  get '/search_pockets' => 'search#pockets'
  get '/search_tips' => 'search#tips'
  get '/search_connections' => 'search#connections'
  get '/search_social_friends' =>  'search#social_friends'
  post '/search_social_friends' =>  'search#social_friends'
  get '/user_following_friends' => 'search#user_following_friends'
  get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
  get '/user_following_groups' => 'search#user_following_groups'
  get '/user_following_hives' => 'search#user_following_hives'
  get '/user_following_pockets' => 'search#user_following_pockets'
  get '/user_following_tips' => 'search#user_following_tips'
  get '/share_type_permission' => 'search#share_type_permission'
  get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
  post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
  post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
  # use_link_thumbnailer
  resources :pictures do
    collection do
      post 'tag'
    end
    member do
      post 'remove_tag', :as => :remove_tag
    end
  end
  match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
  match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]

  resources :files
  match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
  resources :comments

  get '/menu_friend_invitations' => 'friend_invitations#menu_friend_invitations'
  resources :friend_invitations

app/models/group.rb
class Group < ActiveRecord::Base
  include Tenant
  include PublicActivity::Model
  tracked owner: Proc.new { |controller, _model| controller.current_user if controller }

  serialize :admin_ids, Array

  acts_as_followable
  acts_as_follower
  acts_as_taggable_on :allowing_domains, :allowing_locations

  JOIN_TYPES = [
    ['Anyone', :anyone],
    ['Invite only', :invite],
    ['Users with certain email address', :domain],
    ['Users at certain location', :location]
  ]

  GROUP_TYPES = [
    ['General purpose', :general],
    ['Event', :event],
    ['University group', :university],
    ['Enterprise group', :enterprise]
  ]

  COLOR = %w(liteorange orange purple litepurple green liteblue blue)

  before_create :set_color

  validates :title, presence: true

  # extend FriendlyId
  # friendly_id :slug_candidates, use: :slugged
  def to_param
    "#{self.id} #{self.name}".parameterize
  end

  belongs_to :user
  has_many :group_domains # *** THIS IS JUST FOR MIGRATION PURPOSE

  mount_uploader :avatar, AvatarUploader
  mount_uploader :background_image, BackgroundImageUploader
  include GroupObserver
  include TipHiveObject
  include ActsAsSharing

  has_many :pictures, as: :imageable, dependent: :destroy
  attr_accessor :picture_ids

  paginates_per 4

  searchable do
    text :title, :description
    integer :user_id
    string :join_type
    string :group_type
  end

  def slug_candidates
    [
      [:id, :title]
    ]
  end

  def name
    title
  end

  def hives
    following_hives
  end

  def questions
    following_questions
  end

  def members
    user_followers
  end

  def who_can_join
    join_type ? join_type.to_sym : :default
  end

  def allow_domains

  end

  def type
    group_type ? group_type.to_sym : :default
  end

  def admins
    User.where(id: admin_ids)
  end

  def set_color
    self.color = COLOR[rand(COLOR.length)]
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < GroupsController
end

app/views/groups/_bootstrap_switch.html.erb
<script>
  $(document).ready(function (e) {
    var auto_state = "<%= object.is_auto_accept %>";
    $('.bootstrap-switch#group_is_auto_accept').bootstrapSwitch({
      state: auto_state,
      size: 'small',
      onText: 'Yes',
      offText: 'No'
    });
    $('.bootstrap-switch#group_is_auto_accept').siblings('label').removeAttr('for');
  });
</script>

app/views/groups/_form_script.html.erb
<script>
  $(function (e) {
    var $group_join_type = $('#group_join_type');
    var $allowing_domains_group = $('#allowing_domains_group');
    var $allowing_locations_group = $('#allowing_locations_group');
    var join_type = $group_join_type.val();

    $group_join_type.on('change', function (e) {
      join_type = $group_join_type.val();
      displayExtraJoinFields(join_type);
    });

    displayExtraJoinFields(join_type);

    function displayExtraJoinFields(field_type) {
      if (field_type == 'domain') {
        $allowing_domains_group.removeClass('hide');
      } else {
        $allowing_domains_group.addClass('hide');
      }

      if (field_type == 'location') {
        $allowing_locations_group.removeClass('hide');
      } else {
        $allowing_locations_group.addClass('hide');
      }
    }

    $('#allowing_domains').selectize({
      plugins: ['remove_button'],
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });

    $('#allowing_locations').selectize({
      plugins: ['remove_button'],
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });

    $('#group_address').geocomplete({
      // map: '#map-canvas',
      // mapOptions: {
      //   zoom: 14
      // },
      // markerOptions: {
      //   draggable: true
      // }
    }).bind("geocode:result", function(event, result){
      var lat = result.geometry.location.lat();
      var lng = result.geometry.location.lng();
      var address = result.formatted_address;
      $('#group_location').val(address);
      $('#group_latitude').val(lat);
      $('#group_longitude').val(lng);
    });

  });
</script>

app/views/groups/_group_hives.html.haml
.modal#hives-show-modal
  .modal-show-profile.modal-dialog 
    .container-user-profile
      .my-hives-navigation-bar
        .my-hives-navigation-head
          = "All hives in #{group.title}"

      #my-hives-container
        .carousel.slide{ 'data-ride' => 'carousel',id: 'my-hive-list'}
          .hives-list
            .carousel-inner
              - hives.each_slice(75) do |slices| 
                .item
                  %table
                    - slices.each_slice(15) do |hives|
                      %td 
                        - hives.each do |hive|
                          %li
                            = link_to hive.title,hive_path(hive)
            - if hives.size > 75
              %a.left.carousel-control{'data-slide' => 'prev', href: '#my-hive-list'}
                %i.fa.fa-angle-left
              %a.right.carousel-control{'data-slide' => 'next', href: '#my-hive-list'}
                %i.fa.fa-angle-right 
        .clearfix
      .loader#loading
      .hide#pagination-wrapper

:javascript
  
  $(document).ready(function() {
    $('#my-hive-list .carousel-inner > .item:first').addClass('active');
  });    

app/views/groups/_member.html.haml
.friend-request.panel.panel-default
  - background_image_style = friend.background_image.present? ? "background-image: url(#{friend.background_image.medium.url})" : ''
  - if friend.background_image.present?
    .overlay
  .panel-heading{class: friend.color, style: background_image_style}
    .request-profile
      = user_avatar(friend, :medium)
      %br
      = link_to friend.name, user_profile_path(friend), class: 'username active-transition', data: {remote: true}
    - if friend.check_active
      .active-sign
        = image_tag image_path('trending-mark.png')
  .panel-body
    .user-connect{id: "user-connect-#{friend.id}"}
      = render 'shared/title_bars/user_connect', user: friend
    .percent-tab
      .percentage
        = "#{current_user.get_percentage(friend)} %"
      In Common

app/views/groups/_my_groups_script.html.erb
<script>
  $(document).ready(function(e){
    $('select#select-groups').selectize({
      sortField: 'text',
      hideSelected: true
    });

    $(window).load(function () {
      masonrizeGroups();
    });

    function masonrizeGroups() {
      var $container = $('#groups-container');
      // initialize Masonry after all images have loaded
      $container.imagesLoaded( function() {
        $container.masonry({
          columnWidth: 230,
          itemSelector: '.group'
        });
      });

      $container.infinitescroll({
            navSelector  : '.pagination',    // selector for the paged navigation
            nextSelector : '.pagination li.next a',  // selector for the NEXT link (to page 2)
            itemSelector : '.group',     // selector for all items you'll retrieve
            bufferPx     : 40,
            prefill      : true,
            loading: {
              msgText      : "<em>Loading the next set of items...</em>",
              finishedMsg: "<em>You've reached the end.</em>",
              img: '<%= image_url('ajax-loader.gif') %>',
              selector: '#loading'
            }
          },
          // trigger Masonry as a callback
          function( newElements ) {
            // hide new items while they are loading
            var $newElems = $( newElements ).css({ opacity: 0 });
            // ensure that images load before adding to masonry layout
            $newElems.imagesLoaded(function(){
              // show elems now they're ready
              $newElems.animate({ opacity: 1 });
              $container.masonry( 'appended', $newElems, true );
              $container.masonry();
            });
          });
    }
  });
</script>

app/views/groups/_request_invite_modal.html.haml
.modal#group-request-invite-modal
  .modal-dialog
    .modal-content
      = form_for :request_invite, url: request_invite_group_path(@group), html: { role: 'form', class: 'form-inline', style: 'margin-top: 0;' } do |f|
        .modal-header
          %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'modal', type: 'button'} ×
          %h4.modal-title Join Invite
        .modal-body
          .form-group
            = f.email_field :email, placeholder: "Enter your #{@group.group_type == 'university' ? 'university' : 'company'} email address to get an invitation", required: true, class: 'form-control', style: 'width: 450px;'
            = f.submit 'Join', class: 'btn btn-primary'
            %span.help-block We will send you an email to create your account
        .modal-footer
          %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close

app/views/groups/_tips.html.haml
- tips.each do |tip|
  = render 'tips/tip_detail', tip: tip
.clearfix

app/views/groups/create.js.erb
$('#side-group-form').html('<%= j(render('shared/side_bars/group_form')) %>');
$('#side-groups').prepend('<%= j(render('shared/side_bars/group', group: @group)) %>');

app/views/groups/edit.html.haml
.row.form-wrapper
  .col-md-8.col-md-offset-2

    .row
      .col-md-9.col-md-offset-3
        %h1 Editing group

    = render 'form'

    .row
      .col-md-9.col-md-offset-3
        = link_to 'Delete', @group, class: 'btn btn-danger', data: { method: :delete, confirm: 'Are you sure to delete this Group?' }
        = link_to 'Show', @group, class: 'btn btn-default'
        = link_to 'Back', my_groups_path, class: 'btn btn-default'

app/views/groups/members.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/group_title', group: @group

= content_for :filter_bar do
  = render 'shared/filter_bars/group_filter', group: @group

.container-fluid#alphabet-wrapper
  .alphabet
    - ('A'..'Z').each do |char|
      %span
        - logger.info "@members_az[char]: #{@members_az[char].inspect}"
        - if @members_az[char][:count] > 0
          = link_to char, group_members_by_initial_path(initial: char)
        - else
          = "#{char}"
      - if char != 'Z'
        %span
          = '&nbsp;'.html_safe

.container-fluid#friend-request
  - @members.each do |friend|
    = render 'groups/member', friend: friend
  .clearfix
.loader#loading
.hide
  = paginate @members

= render 'users/my_friends_script_v1'

app/views/groups/my_groups.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/my_groups_title'
= content_for :filter_bar do
  = render 'shared/filter_bars/my_group_filter'
.container-fluid#groups-container
  - @groups.each do |group|
    = render 'groups/group', group: group
  .clearfix
.loader#loading
.hide
  = paginate @groups

= render 'groups/my_groups_script'

app/views/groups/new.html.haml
.row.form-wrapper
  .col-md-8.col-md-offset-2

    .row
      .col-md-9.col-md-offset-3
        %h1 New group

    = render 'form'

app/views/groups/request_invite.html.haml
.row
  .col-md-6.col-md-offset-3
    - if @error_text.present?
      .panel.panel-danger{style: 'margin-top: 100px'}
        .panel-heading.text-center
          %h3.panel-title
            %i.fa.fa-minus-circle
            Group joining request failed!
        .panel-body.text-center
          = @error_text
    - else
      .panel.panel-success{style: 'margin-top: 100px'}
        .panel-heading.text-center
          %h3.panel-title
            %i.fa.fa-check-circle
            Group joining request sent!
        .panel-body.text-center
          Your request to join
          %strong #{@group.name}
          group has been sent.

app/views/groups/show.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/group_title', group: @group

= content_for :filter_bar do
  = render 'shared/filter_bars/group_filter', group: @group

- if params[:sort_filter] != 'near_by'
  - if params[:page].blank? || params[:page].to_i == 1
    .container-fluid.tip-container#tip-adding-container
      = render 'tips/tip_adding_form', group_id: @group.id
  .container-fluid.tip-container#tips-feed-container
    = render 'groups/tips', tips: @tips
  .loader#loading
  .hide#pagination-wrapper
    = paginate @tips
- else
  = render 'shared/near_by_on_map', tips: @tips
  .loader#loading
  .hide#pagination-wrapper
    = @tips

= render 'tips/readmore_script'