config/routes.rb
require 'subdomain'
TipHive::Application.routes.draw do

  resources :action_logs

  post '/tiphive_settings' => 'tiphive_settings#index'
  get '/switch_group' => 'tiphive_settings#switch_domain_setting'
  resources :tiphive_settings do 
    collection do
      post :get_domain
      get :hives
    end
  end

  get 'sidebar/tips'
  get 'sidebar/questions'
  get 'sidebar/my_hives'
  get 'sidebar/my_groups'
  get 'sidebar/my_friends'

  constraints(Subdomain) do
    get '/' => 'domains#home'
  end

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        resources :users
        resources :comments
        resources :groups do
          resources :tips
        end
        resources :hives do
          resources :tips
        end
        resources :pockets do
          resources :tips
        end
        resources :tips
        resources :questions

        post '/sign_in' => 'sessions#create'
        delete '/sign_out' => 'sessions#destroy'
        post '/sign_up' => 'registrations#create'
        get '/me' => 'users#me'
        get '/friends' => 'users#my_friends'

        get '/search' => 'search#index'
        get '/search_mentions' => 'search#mentions'
        get '/search_users' => 'search#users'
        get '/search_groups' => 'search#groups'
        get '/search_invitable_groups' => 'search#invitable_groups'
        get '/search_users_and_groups' => 'search#users_and_groups'
        get '/search_hives' => 'search#hives'
        get '/search_pockets' => 'search#pockets'
        get '/search_tips' => 'search#tips'
        get '/search_connections' => 'search#connections'
        get '/user_following_friends' => 'search#user_following_friends'
        get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
        get '/user_following_groups' => 'search#user_following_groups'
        get '/user_following_hives' => 'search#user_following_hives'
        get '/user_following_pockets' => 'search#user_following_pockets'
        get '/user_following_tips' => 'search#user_following_tips'
        get '/share_type_permission' => 'search#share_type_permission'
        get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
        post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
        post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
        # use_link_thumbnailer
        resources :pictures
        match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
        match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]
        match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
        resources :comments

        resources :files

        get '/validates_invitation_token' => 'invitation_requests#validates_invitation_token', as: :validates_invitation_token
        get '/invitation_request_from_token' => 'invitation_requests#invitation_request_from_token', as: :invitation_request_from_token
        get '/invitation_requests/:id/accept' => 'invitation_requests#accept', as: :accept_invitation_request
        get '/menu_invitation_requests' => 'invitation_requests#menu_invitation_requests'
        resources :invitation_requests

        resources :groups do
          resources :hives
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :request_invite
            post :request_invite
            get :members
            get :no_access
          end
        end
        get '/groups/:id/members/:initial' => 'groups#members', as: :group_members_by_initial
        get '/domains/:id/members/:initial' => 'domains#members', as: :domain_members_by_initial

        get '/my_groups' => 'groups#my_groups'
        get '/menu_groups' => 'groups#menu_groups'

        resources :tip_links do
          collection do
            get '/fetch' => 'tip_links#fetch'
          end
        end
        resources :tips do
          post '/like' => 'tips#like'
          post '/unlike' => 'tips#unlike'
          get '/get_tip' => 'tips#get_tip'
          post '/flag' => 'tips#flag'
          post '/update_tip_location' => 'tips#update_tip_location'
          collection do
            post '/business' => 'tips#business'
          end
          member do
            get :share
            get :hives_and_pockets
          end
        end

        resources :questions do
          post '/like' => 'questions#like'
          post '/unlike' => 'questions#unlike'
          post '/flag' => 'questions#flag'
          member do
            get :add_existing_tip
            get :add_comment
            get :hives_and_pockets
            get :shared_objects
          end
        end


        resources :pockets do
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :object_setting_model
            post :object_setting
            put :object_setting
          end
        end
        get '/my_pockets' => 'pockets#my_pockets'

        resources :hives do
          resources :pockets
          resources :questions
          get '/my_pockets' => 'pockets#my_pockets'
          member do
            get :leave
            get :join
            get :share
            get :friends
            post :object_setting
            put :object_setting
          end
          collection do
            get :following_pockets
          end
        end
        get '/my_hives' => 'hives#my_hives'
        get '/menu_hives' => 'hives#menu_hives'

        get '/tips' => 'tips#index', as: :user_root

        resources :users do
          resources :hives
          resources :questions
          member do
            get :friends
          end
        end
        resources :domains do
          member do
            get :members
            get :billing
            get :share
          end
        end

        post '/upload_image' => 'pictures#upload_image'
        post '/upload_background_image' => 'pictures#upload_background_image'
        post '/upload_avatar_image' => 'pictures#upload_avatar_image'
        post '/upload_avatar' => 'users#upload_avatar'
        get '/select_avatar' => 'users#select_avatar'
        get '/email_notifications' => 'users#email_notifications'
        post '/email_notifications' => 'users#email_notifications'
        post '/add_as_friend/:user_id' => 'users#add_as_friend', as: :add_as_friend
        post '/add_as_friends' => 'users#add_as_friends', as: :add_as_friends
        post '/unfriend/:user_id' => 'users#unfriend', as: :unfriend
        get '/status_with/:user_id' => 'users#status_with', as: :status_with

        get '/users/:id' => 'users#show', as: :user_profile
        get '/my_friends/:initial' => 'users#my_friends', as: :my_friends_by_initial
        get '/my_friends' => 'users#my_friends'
        get '/add_friends' => 'users#add_friends'
        post '/add_friends' => 'users#add_friends'
        get '/count_element' => 'users#user_count_element'

        post '/connect_following_objects' => 'home#connect_following_objects', as: :connect_following_objects
        post '/disconnect_following_objects' => 'home#disconnect_following_objects', as: :disconnect_following_objects
        post '/update_background_image_position' => 'home#update_background_image_position'
      end

      get '*unmatched_route', to: 'application#raise_not_found!'
      post '*unmatched_route', to: 'application#raise_not_found!'
      put '*unmatched_route', to: 'application#raise_not_found!'
      delete '*unmatched_route', to: 'application#raise_not_found!'
    end
  end

  get '/search' => 'search#index'
  get '/search_mentions' => 'search#mentions'
  get '/search_users' => 'search#users'
  get '/search_groups' => 'search#groups'
  get '/search_invitable_groups' => 'search#invitable_groups'
  get '/search_users_and_groups' => 'search#users_and_groups'
  get '/search_hives' => 'search#hives'
  get '/search_pockets' => 'search#pockets'
  get '/search_tips' => 'search#tips'
  get '/search_connections' => 'search#connections'
  get '/search_social_friends' =>  'search#social_friends'
  post '/search_social_friends' =>  'search#social_friends'
  get '/user_following_friends' => 'search#user_following_friends'
  get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
  get '/user_following_groups' => 'search#user_following_groups'
  get '/user_following_hives' => 'search#user_following_hives'
  get '/user_following_pockets' => 'search#user_following_pockets'
  get '/user_following_tips' => 'search#user_following_tips'
  get '/share_type_permission' => 'search#share_type_permission'
  get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
  post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
  post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
  # use_link_thumbnailer
  resources :pictures do
    collection do
      post 'tag'
    end
    member do
      post 'remove_tag', :as => :remove_tag
    end
  end
  match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
  match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]

  resources :files
  match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
  resources :comments

  get '/menu_friend_invitations' => 'friend_invitations#menu_friend_invitations'
  resources :friend_invitations

app/models/domain.rb
class Domain < ActiveRecord::Base
  acts_as_followable
  acts_as_follower

  include DomainObserver

  # Constants
  RESERVED_DOMAINS = %w(
    about
    api
    assets
    beta
    cdn
    ci
    db
    dev
    development
    enterprise
    errors
    newprod
    prod
    production
    staging
    team
    tiphive
    www
  )

  # Assocations
  has_many :comments
  has_many :friend_invitations, inverse_of: :domain
  has_many :groups
  has_many :hives
  has_many :pictures
  has_many :pockets
  has_many :questions
  has_many :tips
  belongs_to :user

  mount_uploader :logo, LogoUploader
  mount_uploader :background, BackgroundImageUploader

  # Validations
  validates :name, presence: true, uniqueness: true,
            exclusion:       { in: RESERVED_DOMAINS, message: '%{value} is reserved.' }

  # Callbacks
  before_validation :parameterize_name
  before_create :activate

  # Scopes
  scope :active, -> { where(active: true) }

  alias_attribute :title, :name

  def full_name
    %w(staging beta).include?(Rails.env) ? "#{name}.#{Rails.env}.tiphive.com" : "#{name}.tiphive.com"
  end

  def root?
    Domain::RESERVED_DOMAINS.include?(name) || !name.present?
  end

  def logo_path
    root? ? 'logo.png' : logo.thumb.url
  end

  def self.current
    Thread.current[:domain] || Domain.root
  end

  def self.current=(domain)
    Thread.current[:domain] = domain
  end

  def to_param
    "#{id} #{name}".parameterize
  end

  def users_count(date = Time.now)
    @users_count ||= user_followers.where('follows.created_at < ?', date).count
  end

  def members
    user_followers.where('users.id != ?', user.id)
  end

  def status_with(member)
    return :is_me if user_id == member.id
    is_followed = member.following?(self)
    return :is_member if is_followed
    return :is_nothing if !is_followed
  end

  def price
    return 0.0 if @users_count.nil? || @users_count.zero?
    if @users_count < 100
      100
    elsif @users_count.between?(100, 4999)
      @users_count
    elsif @users_count.between?(5000, 9999)
      0.9 * @users_count
    else
      0.5 * @users_count
    end
  end

  private

  def parameterize_name
    return 'unnamed' if name.blank?
    self.name = name.parameterize
  end

  def activate
    self.active = true
  end

  class << self
    def root
      @root ||= new(active: true).freeze
    end
  end
end

app/controllers/api/v1/domains_controller.rb
class Api::V1::DomainsController < DomainsController
  def index
    @domains = current_user.following_domains.reject { |d| d.id.nil? }
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_filter :authenticate_user_from_token!
  before_action :authenticate_user!, except: [:home]
  layout 'domain', only: [:home]


  def index
    @domain = current_user.domains.new
  end

  def create
    @domain = current_user.domains.new(domain_params)
    if @domain.save
      current_user.follow @domain
      respond_to do |format|
        format.html { redirect_to domains_path, notice: 'Domain was successfully created' }
        format.js {}
        format.json { render template: 'api/v1/domains/show' }
      end
    else
      respond_to do |format|
        format.html { render :index }
        format.js {}
        format.json do
          render json: { response: { error: @domain.errors, full_messages: @domain.errors.full_messages },
                         status:   :fail, message: @domain.errors.full_messages.join(', ')
                 }
        end
      end
    end
  end

  def home
    redirect_to tips_path if user_signed_in?
  end

  def show
    @domain = current_user.domains.find(params[:id])
  end

  def destroy
    @domain = current_user.domains.find(params[:id])
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_path, notice: 'Domain deleted' }
      format.json { render json: { response: {}, status: :success, message: 'Domain deleted' } }
    end
  end

  def update
    @domain = current_user.domains.find(params[:id])
    if @domain.update(domain_params)
      respond_to do |format|
        format.html { redirect_to domains_path, notice: 'Domain was successfully updated' }
        format.js {}
        format.json { render template: 'api/v1/domains/show' }
      end
    else
      respond_to do |format|
        format.html { render :show }
        format.js {}
        format.json do
          render json: { response: { error: @domain.errors, full_messages: @domain.errors.full_messages },
                         status:   :fail, message: @domain.errors.full_messages.join(', ')
                 }
        end
      end
    end

  end

  def members
    @domain     = current_user.domains.find(params[:id])
    @members_az = {}
    ('A'..'Z').each do |char|
      char_members      = {
        count:   @domain.user_followers.where("first_name LIKE '#{char}%'").count,
        members: @domain.user_followers.where("first_name LIKE '#{char}%'").order(:first_name)
      }
      @members_az[char] = char_members
    end
    if params[:initial].present?
      @members = @domain.user_followers.where("first_name LIKE '#{params[:initial]}%'").order(:first_name).page params[:page]
    else
      @members = @domain.user_followers.order(:first_name).page params[:page]
    end

    respond_to do |format|
      format.html {}
      format.json {}
    end
  end

  def share
    @domain                       = current_user.domains.find(params[:id])
    @connected_friends_and_groups = @selected_friends_and_groups = @domain.members - [current_user]
  end

  def billing
    @domain = current_user.domains.find(params[:id])
  end

  def upload_image
    @domain = current_user.domains.find(params[:id])
    respond_to do |format|
      if @domain.update(image_params)
        format.html { render :show }
        format.json {}
      else
        format.html { render :show }
        format.json do
          render json: { response: { error: @domain.errors, full_messages: @domain.errors.full_messages },
                         status: :fail, message: @domain.errors.full_messages.join(', ') }
        end
      end
    end
  end

  private
  def domain_params
    params.require(:domain).permit(:name, :logo, :background, :active, :background_cache, :logo_cache,
                                   :remove_background, :remove_logo, :domain_id)
  end

  def image_params
    params.require(:domain_image).permit(:title, :logo, :background)
  end
end

app/views/domains/_bootstrap_switch.html.erb
<script>
  $(document).ready(function (e) {
    $('input.checkbox').bootstrapSwitch({
      onColor: 'success',
      size: 'small',
      onText: 'Active',
      offText: 'No',
      onSwitchChange: function updateDomain(event, state) {
        var id = $(this).data('id');
        $('li#domain-list-'+id).toggle();
        $.ajax({
            type: 'PUT',
            url: '/domains/' + id,
            dataType: "JSON",
            data: {"domain[active]": state}
        });
      }
    });
  });
</script>

app/views/domains/_domain.html.haml
.container-fluid
  .row.domain-setting
    .col-md-3.col-md-offset-2
      = domain.full_name
    .col-md-3
      %input.checkbox{type: 'checkbox', name: 'status', checked: domain.active, 'data-id' => domain.id }
    .col-md-3
      = link_to 'Settings', domain_path(domain)
= render 'domains/bootstrap_switch'

app/views/domains/_form.html.haml
= form_for(@domain, html: { role: 'form', class: 'form-horizontal' }) do |f|
  .form-group
    = f.label 'Domain url', class: 'col-md-3 control-label'
    .col-md-6
      .input-group.fileinput-new
        = f.text_field :name, required: true, class: 'form-control'
        %span.input-group-addon.btn.btn-default.btn-file
          = @domain.full_name
  .form-group
    = f.label :logo, class: 'col-md-3 control-label'
    .col-md-6
      =# f.file_field :background_image, class: 'form-control'
      = f.hidden_field :logo_cache
      .fileinput.fileinput-new.input-group{'data-provides' => 'fileinput'}
        .image-upload-actions
          %span.btn.btn-primary.fileinput-button
            %span Upload Logo
            %input#image-logoupload{ type: 'file', name: 'domain_image[logo]', multiple: 'multiple', class: 'btn btn-primary', data: { url: upload_image_domain_path(@domain) } }
          %span.ajax-loader.hide#ajax-loader  
  .form-group#logo-domain      
    - if @domain.logo.present?
      .col-md-3
      .col-md-9
        .form-thumb
          = image_tag(@domain.logo.small.url)
          %br
          %label
            = f.check_box :remove_logo
            Remove logo        
  .form-group
    = f.label 'Image homepage', class: 'col-md-3 control-label'
    .col-md-6
      =# f.file_field :background_image, class: 'form-control'
      = f.hidden_field :background_cache
      .fileinput.fileinput-new.input-group{'data-provides' => 'fileinput'}
        .image-upload-actions
          %span.btn.btn-primary.fileinput-button
            %span Upload Background
            %input#image-backgroundupload{ type: 'file', name: 'domain_image[background]', multiple: 'multiple', class: 'btn btn-primary', data: { url: upload_image_domain_path(@domain) } }
          %span.ajax-loader.hide#ajax-loader-bg
  .form-group#background-domain
    - if @domain.background.present?
      .col-md-3
      .col-md-9
        .form-thumb
          = image_tag(@domain.background.small.url)
          %br
          %label
            = f.check_box :remove_background
            Remove background image 
  .form-group
    .col-md9.col-md-offset-3
      = f.submit class: 'btn btn-primary'
      = link_to 'Delete', @domain, class: 'btn btn-danger', data: { method: :delete, confirm: 'Are you sure to delete this Domain?' } if @domain.persisted?

= render 'domains/upload_image_script', domain: @domain

app/views/domains/_login_form.html.haml
.row
  .col-md-6.col-md-offset-3.sign-in-wrapper
    .panel.panel-default.panel-sign-in
      .panel-body
        %form.form
          .form-group
            %input.form-control{type: 'email', placeholder: 'your work email address'}
          .form-group
            %input.form-control{type: 'password', placeholder: 'Password'}
          .form-group
            %input.button-domain{type: 'submit', value: 'Login'}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            %a{href: '/'} Forgot password?

app/views/domains/_share_modal.html.haml
.modal#domain-share-modal.share-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'modal', type: 'button'} ×
        %h4.modal-title Add member to domain
      .modal-body
        %ul.nav.nav-pills
          %li.active
            %a{href: '#share', 'data-toggle'=>'tab'} Share
          %li
            %a{href: '#invite', 'data-toggle'=>'tab'} Invite by email
          %li
            %a{href: '#share-link', 'data-toggle'=>'tab'} Share link
        .tab-content.popup-form
          #share.tab-pane.active
            = form_for @domain, url: share_domain_path(@domain), html: { role: 'form', class: 'form-horizontal', data: { remote: true } } do |f|
              = f.hidden_field :id
              .form-group
                = f.label 'Share', class: 'col-md-1 control-label'
                .col-md-11
                  = render 'search/friends_and_groups_select_for_sharing', f: f, object: @domain, selected_friends_and_groups: @selected_friends_and_groups
                .col-md-1.control-label
                .col-md-11
                  = 'Sharing with' if @connected_friends_and_groups.map{ |u| u.class.name }.include? 'User'
                  - @connected_friends_and_groups.each do |u|
                    = user_avatar(u, :tiny)

          #invite.tab-pane
            = render 'users/add_friends_modules/email', connectable: @domain
          #share-link.tab-pane
            .share-area
              Share with
              - domain_image = @domain.background.present? ? @domain.background.medium.url : image_url('pockets-no-images.png')
              - image = image_url(domain_image)
              = render 'shared/social_share', object: @domain, content: @domain.name, image: image
          = render 'search/friends_and_groups_select_for_sharing_script', object: @domain

      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close

app/views/domains/_sign_up.html.haml
.row
  .col-md-6.col-md-offset-3.sign-in-wrapper
    .panel.panel-default.panel-sign-up
      .panel-body
        %form.form
          .form-group
            %input.form-control{type: 'email', placeholder: 'your work email address'}
          .form-group
            %input.button-domain{type: 'submit', value: 'Sign Up'}
          %br
          %p Check your inbox for an email with

          %p the link to create your account
          %br
        %form.form
          %p Don't have a company email address?
          .form-group
            %input.form-control{type: 'email', placeholder: 'your email address'}
          .form-group
            %input.button-domain{type: 'submit', value: 'Request invite'}

app/views/domains/_upload_image_script.html.erb
<script type="text/javascript">
  $('#image-logoupload').fileupload({
    dataType: 'json',
    method: 'POST',
    add: function (e, data) {
      $('#ajax-loader').removeClass('hide');
      data.submit();
    },
    progressall: function (e, data) {
      var progress = parseInt(data.loaded / data.total * 100, 10);
    },
    done: function (e, data) {
      $('#ajax-loader').addClass('hide');
      var domain = JSON.parse(data.jqXHR.responseText);
      if (domain.status == 'fail')
      {
        $('#logo-domain').after(domain.message);
      }
      else
      {
        var $image_link = $('<div>');
        var $div_col = $('<div>');
        var $div_image = $('<div>');
        var $image = $('<img>');
        var $delete_button = $('<label>');
        $delete_button.append('<input type="hidden" value="0" name="domain[remove_logo]">');
        $delete_button.append('<input id="domain_remove_logo" type="checkbox" value="1" name="domain[remove_logo]">'); 
        $delete_button.append('Remove Logo')
        //var $delete_button = $('<button class="btn-remove-picture glyphicon glyphicon-remove btn btn-danger btn-sm" type="button" data-picture-id="'+domain.id+'">')
        //$delete_button.on('click', processRemovePicture);
        $div_col.addClass('col-md-3');
        $div_image.addClass('col-md-9') 
        $image.attr('src', domain.logo.logo.small.url);
        $image_link.addClass('form-thumb');
        $image_link.append($image);
        $div_image.append($image_link);
        $div_image.append($delete_button);
        //$div_image.after($image_link);
        //$image_link.append($delete_button);
        $('#logo-domain').empty();
        $('#logo-domain').append($div_col);
        $('#logo-domain').append($div_image);

        //$('#tip_picture_ids').val(picture_ids);
      }
    }
  });

  $('#image-backgroundupload').fileupload({
    dataType: 'json',
    method: 'POST',
    add: function (e, data) {
      $('#ajax-loader-bg').removeClass('hide');
      data.submit();
    },
    progressall: function (e, data) {
      var progress = parseInt(data.loaded / data.total * 100, 10);
    },
    done: function (e, data) {
      $('#ajax-loader-bg').addClass('hide');
      var domain = JSON.parse(data.jqXHR.responseText);
      if (domain.status == 'fail')
      {
        $('#background-domain').after(domain.message);
      }
      else
      {
        var $image_link = $('<div>');
        var $div_col = $('<div>');
        var $div_image = $('<div>');
        var $image = $('<img>');
        var $delete_button = $('<label>');
        $delete_button.append('<input type="hidden" value="0" name="domain[remove_background]">');
        $delete_button.append('<input id="domain_remove_background" type="checkbox" value="1" name="domain[remove_background]">'); 
        $delete_button.append('Remove Background')
        $div_col.addClass('col-md-3');
        $div_image.addClass('col-md-9') 
        $image.attr('src', domain.background.background.small.url);
        $image_link.addClass('form-thumb');
        $image_link.append($image);
        $div_image.append($image_link);
        $div_image.append($delete_button);
        //$div_image.after($image_link);
        //$image_link.append($delete_button);
        $('#background-domain').empty();
        $('#background-domain').append($div_col);
        $('#background-domain').append($div_image);

        //$('#tip_picture_ids').val(picture_ids);
      }
    }
  });

</script>

app/views/domains/billing.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/simple_title', title: 'Domain Settings', content: "Domain: #{@domain.name}"
= content_for :filter_bar do
  = render 'shared/filter_bars/settings_domain'

.row.form-wrapper
  .col-md-8.col-md-offset-2
    .row
      .col-md-9.col-md-offset-4
        %h3 Usage
    %form.form-horizontal
      - if @domain.errors.any?
        #error_explanation.alert.alert-danger
          %h2= "#{pluralize(@domain.errors.count, 'error')} prohibited this domain from being saved:"
          %ul
            - @domain.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        %label.col-md-4.control-label On #{Date.today.beginning_of_month.strftime('%B')} 1, this domain had
        .col-md-3
          .form-control
            = @domain.users_count(Date.today.beginning_of_month)
      .form-group
        %label.col-md-4.control-label Your cost per user per month is
        .col-md-3
          .form-control
            $
            = (@domain.price / @domain.users_count)
        %a{'data-toggle'=>'modal', href: '#SeePrice'} See pricing

      .form-group
        %label.col-md-4.control-label Your total cost for this month is
        .col-md-3
          .form-control
            $
            = @domain.price

#SeePrice.modal
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        .button.close{ type: 'button', 'data-dismiss'=>'modal', 'aria-hidden'=>'true'}
          x
        %h4.modal-titel Pricing
      .modal-body
        %table.table.table-bordered
          %tbody
            %tr
              %td Users
              %td Price
            %tr
              %td <100
              %td $100 / month
            %tr
              %td 100-5,000
              %td $1 / user /month
            %tr
              %td 5,000 - 10,000
              %td $0,09 / user / month
            %tr
              %td >10,000
              %td $9,000 / user / month
      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close

app/views/domains/home.html.haml
.container-fluid
  .row
    .login-link
      %ul.nav-button.text-center
        %li
          %a.btn.btn-primary.btn-md{href: new_user_session_path} Log In
        %li
          %a.btn.btn-primary.btn-md{href: new_user_registration_path} Sign Up

app/views/domains/index.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/simple_title', title: 'Settings'
= content_for :filter_bar do
  = render 'shared/filter_bars/settings_filter'
.row.form-wrapper
  .col-md-8.col-md-offset-2
    .row
      .col-md-9.col-md-offset-3
        %h3 Create a domain
    =# render 'form'
    = form_for(@domain, html: { role: 'form', class: 'form-horizontal' }) do |f|
      .form-group
      = f.label 'Domain url', class: 'col-md-3 control-label'
      .col-md-6
        .input-group.fileinput-new
          = f.text_field :name, required: true, class: 'form-control'
          %span.input-group-addon.btn.btn-default.btn-file
            = @domain.full_name
      = f.submit class: 'btn btn-primary col-md-3'
%br
.divider
- if current_user.domains.select(&:persisted?).any?
  .row
    .col-md-7.col-md-offset-5
      %h3 Your domains
    = render(current_user.domains.select(&:persisted?))

app/views/domains/members.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/simple_title', title: 'Domain Settings', content: "Domain: #{@domain.name}"
= content_for :filter_bar do
  = render 'shared/filter_bars/settings_domain'


.container-fluid#alphabet-wrapper
  .alphabet
    - ('A'..'Z').each do |char|
      %span
        - logger.info "@members_az[char]: #{@members_az[char].inspect}"
        - if @members_az[char][:count] > 0
          = link_to char, domain_members_by_initial_path(initial: char)
        - else
          = "#{char}"
      - if char != 'Z'
        %span
          = '&middot;'.html_safe

.container-fluid#friends-container
  - @members.each do |friend|
    = render 'users/friend', friend: friend
  .clearfix
.loader#loading
.hide
  = paginate @members

= render 'users/my_friends_script'

app/views/domains/share.js.erb
$('.modal').modal('hide');
$('#primary-modal').html('<%= j(render('domains/share_modal')) %>');
$('#domain-share-modal').modal('show');

app/views/domains/show.html.haml
= content_for :title_bar do
  = render 'shared/title_bars/domains_title', locals: { title: 'Domain Settings'}
= content_for :filter_bar do
  = render 'shared/filter_bars/settings_domain'
%br
= render 'form', locals: { domain: @domain}
.divider
- if current_user.domains.select(&:persisted?).any?
  .row
    .col-md-9.col-md-offset-5
      %h3 Your domains
    = render(current_user.domains.select(&:persisted?))