config/routes.rb
require 'subdomain'
TipHive::Application.routes.draw do

  resources :action_logs

  post '/tiphive_settings' => 'tiphive_settings#index'
  get '/switch_group' => 'tiphive_settings#switch_domain_setting'
  resources :tiphive_settings do 
    collection do
      post :get_domain
      get :hives
    end
  end

  get 'sidebar/tips'
  get 'sidebar/questions'
  get 'sidebar/my_hives'
  get 'sidebar/my_groups'
  get 'sidebar/my_friends'

  constraints(Subdomain) do
    get '/' => 'domains#home'
  end

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      devise_scope :user do
        resources :users
        resources :comments
        resources :groups do
          resources :tips
        end
        resources :hives do
          resources :tips
        end
        resources :pockets do
          resources :tips
        end
        resources :tips
        resources :questions

        post '/sign_in' => 'sessions#create'
        delete '/sign_out' => 'sessions#destroy'
        post '/sign_up' => 'registrations#create'
        get '/me' => 'users#me'
        get '/friends' => 'users#my_friends'

        get '/search' => 'search#index'
        get '/search_mentions' => 'search#mentions'
        get '/search_users' => 'search#users'
        get '/search_groups' => 'search#groups'
        get '/search_invitable_groups' => 'search#invitable_groups'
        get '/search_users_and_groups' => 'search#users_and_groups'
        get '/search_hives' => 'search#hives'
        get '/search_pockets' => 'search#pockets'
        get '/search_tips' => 'search#tips'
        get '/search_connections' => 'search#connections'
        get '/user_following_friends' => 'search#user_following_friends'
        get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
        get '/user_following_groups' => 'search#user_following_groups'
        get '/user_following_hives' => 'search#user_following_hives'
        get '/user_following_pockets' => 'search#user_following_pockets'
        get '/user_following_tips' => 'search#user_following_tips'
        get '/share_type_permission' => 'search#share_type_permission'
        get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
        post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
        post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
        # use_link_thumbnailer
        resources :pictures
        match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
        match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]
        match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
        resources :comments

        resources :files

        get '/validates_invitation_token' => 'invitation_requests#validates_invitation_token', as: :validates_invitation_token
        get '/invitation_request_from_token' => 'invitation_requests#invitation_request_from_token', as: :invitation_request_from_token
        get '/invitation_requests/:id/accept' => 'invitation_requests#accept', as: :accept_invitation_request
        get '/menu_invitation_requests' => 'invitation_requests#menu_invitation_requests'
        resources :invitation_requests

        resources :groups do
          resources :hives
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :request_invite
            post :request_invite
            get :members
            get :no_access
          end
        end
        get '/groups/:id/members/:initial' => 'groups#members', as: :group_members_by_initial
        get '/domains/:id/members/:initial' => 'domains#members', as: :domain_members_by_initial

        get '/my_groups' => 'groups#my_groups'
        get '/menu_groups' => 'groups#menu_groups'

        resources :tip_links do
          collection do
            get '/fetch' => 'tip_links#fetch'
          end
        end
        resources :tips do
          post '/like' => 'tips#like'
          post '/unlike' => 'tips#unlike'
          get '/get_tip' => 'tips#get_tip'
          post '/flag' => 'tips#flag'
          post '/update_tip_location' => 'tips#update_tip_location'
          collection do
            post '/business' => 'tips#business'
          end
          member do
            get :share
            get :hives_and_pockets
          end
        end

        resources :questions do
          post '/like' => 'questions#like'
          post '/unlike' => 'questions#unlike'
          post '/flag' => 'questions#flag'
          member do
            get :add_existing_tip
            get :add_comment
            get :hives_and_pockets
            get :shared_objects
          end
        end


        resources :pockets do
          resources :questions
          member do
            get :leave
            get :join
            get :share
            get :object_setting_model
            post :object_setting
            put :object_setting
          end
        end
        get '/my_pockets' => 'pockets#my_pockets'

        resources :hives do
          resources :pockets
          resources :questions
          get '/my_pockets' => 'pockets#my_pockets'
          member do
            get :leave
            get :join
            get :share
            get :friends
            post :object_setting
            put :object_setting
          end
          collection do
            get :following_pockets
          end
        end
        get '/my_hives' => 'hives#my_hives'
        get '/menu_hives' => 'hives#menu_hives'

        get '/tips' => 'tips#index', as: :user_root

        resources :users do
          resources :hives
          resources :questions
          member do
            get :friends
          end
        end
        resources :domains do
          member do
            get :members
            get :billing
            get :share
          end
        end

        post '/upload_image' => 'pictures#upload_image'
        post '/upload_background_image' => 'pictures#upload_background_image'
        post '/upload_avatar_image' => 'pictures#upload_avatar_image'
        post '/upload_avatar' => 'users#upload_avatar'
        get '/select_avatar' => 'users#select_avatar'
        get '/email_notifications' => 'users#email_notifications'
        post '/email_notifications' => 'users#email_notifications'
        post '/add_as_friend/:user_id' => 'users#add_as_friend', as: :add_as_friend
        post '/add_as_friends' => 'users#add_as_friends', as: :add_as_friends
        post '/unfriend/:user_id' => 'users#unfriend', as: :unfriend
        get '/status_with/:user_id' => 'users#status_with', as: :status_with

        get '/users/:id' => 'users#show', as: :user_profile
        get '/my_friends/:initial' => 'users#my_friends', as: :my_friends_by_initial
        get '/my_friends' => 'users#my_friends'
        get '/add_friends' => 'users#add_friends'
        post '/add_friends' => 'users#add_friends'
        get '/count_element' => 'users#user_count_element'

        post '/connect_following_objects' => 'home#connect_following_objects', as: :connect_following_objects
        post '/disconnect_following_objects' => 'home#disconnect_following_objects', as: :disconnect_following_objects
        post '/update_background_image_position' => 'home#update_background_image_position'
      end

      get '*unmatched_route', to: 'application#raise_not_found!'
      post '*unmatched_route', to: 'application#raise_not_found!'
      put '*unmatched_route', to: 'application#raise_not_found!'
      delete '*unmatched_route', to: 'application#raise_not_found!'
    end
  end

  get '/search' => 'search#index'
  get '/search_mentions' => 'search#mentions'
  get '/search_users' => 'search#users'
  get '/search_groups' => 'search#groups'
  get '/search_invitable_groups' => 'search#invitable_groups'
  get '/search_users_and_groups' => 'search#users_and_groups'
  get '/search_hives' => 'search#hives'
  get '/search_pockets' => 'search#pockets'
  get '/search_tips' => 'search#tips'
  get '/search_connections' => 'search#connections'
  get '/search_social_friends' =>  'search#social_friends'
  post '/search_social_friends' =>  'search#social_friends'
  get '/user_following_friends' => 'search#user_following_friends'
  get '/user_following_friends_and_groups' => 'search#user_following_friends_and_groups'
  get '/user_following_groups' => 'search#user_following_groups'
  get '/user_following_hives' => 'search#user_following_hives'
  get '/user_following_pockets' => 'search#user_following_pockets'
  get '/user_following_tips' => 'search#user_following_tips'
  get '/share_type_permission' => 'search#share_type_permission'
  get '/hives_following_users_and_groups' => 'search#hives_following_users_and_groups'
  post '/connect_sharing_objects' => 'home#connect_sharing_objects', as: :connect_sharing_objects
  post '/disconnect_sharing_objects' => 'home#disconnect_sharing_objects', as: :disconnect_sharing_objects
  # use_link_thumbnailer
  resources :pictures do
    collection do
      post 'tag'
    end
    member do
      post 'remove_tag', :as => :remove_tag
    end
  end
  match '/upload_picture', controller: :pictures, action: :upload, via: [:post, :put, :patch]
  match '/upload_comment_picture', controller: :pictures, action: :upload_comment_picture, via: [:post, :put, :patch]

  resources :files
  match '/upload_file', controller: :files, action: :upload, via: [:post, :put, :patch]
  resources :comments

  get '/menu_friend_invitations' => 'friend_invitations#menu_friend_invitations'
  resources :friend_invitations

app/models/picture.rb
class Picture < ActiveRecord::Base
  include Tenant
  acts_as_taggable_on :users
  belongs_to :imageable, polymorphic: true
  belongs_to :user

  attr_accessor :images

  mount_uploader :image, ImageUploader

  validates :image, presence: true

  def width
    MiniMagick::Image.open(image.path)[:width] rescue nil
  end
end

app/controllers/api/v1/pictures_controller.rb
class Api::V1::PicturesController < PicturesController
end

app/views/pictures/_form.html.haml
= form_for @picture do |f|
  - if @picture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@picture.errors.count, 'error')} prohibited this picture from being saved:"
      %ul
        - @picture.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :imageable_id
    = f.number_field :imageable_id
  .field
    = f.label :imageable_type
    = f.text_field :imageable_type
  .actions
    = f.submit 'Save'

app/views/pictures/_picture.html.erb
<!-- Teefan: I don't like inline CSS - TODO: should be refactored -->
<style>
.tag {
  position: relative;
  height: 150px;
}
.name_list {
  display: inline;
}
.carousel-control {
  bottom: 200px;
  width: 0;
}
</style>

<% object = @picture %>

<script>
  $(document).ready(function(e){
    $('#<%= 'tag' + picture.id.to_s%>').selectize({
      valueField: 'name',
      labelField: 'name',
      searchField: 'name',
      sortField: 'kind_id',
      persist: true,
      plugins: ['remove_button'],
      preload: 'focus',
      render: {
        item: function(item, escape) {
          return '<div class="item"><span class="label label-info">' + escape(item['kind_id'].split('-')[0]) + '</span>' + escape(item['name']) + '</div>';
        },
        option: function(item, escape) {
          return '<div class="option"><span class="label label-default">' + escape(item['kind_id'].split('-')[0]) + '</span>' + escape(item['name']) + '</div>';
        }
      },
      load: function(query, callback) {
        if (!query.length) {
          query = '';
        }
        $.ajax({
          url: '<%= user_following_friends_and_groups_path(format: :json) %>',
          type: 'GET',
          dataType: 'json',
          data: {
            q: query
          },
          error: function() {
            callback();
          },
          success: function(res) {
            callback(res);
          }
        });
      },
      onItemAdd: function(value, $item) {
        $.ajax({
          url: '<%= connect_sharing_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', items_list: [value] }
        });

        $.ajax({
          url: '<%= connect_following_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'following', items_list: [value] }
        });
      },
      onItemRemove: function(value) {
        $.ajax({
          url: '<%= disconnect_sharing_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', items_list: [value] }
        });
        $.ajax({
          url: '<%= disconnect_following_objects_path(format: :json) %>',
          type: 'POST',
          data: { id: '<%= object.id %>', kind: '<%= object.class.name %>', type: 'following', items_list: [value] }
        });
      }
    });

    $('.carousel-inner').each(function() {
      if ($(this).children('div').length === 1) $(this).siblings('.carousel-control, .carousel-indicators').hide();
    });
  });
</script>

app/views/pictures/_show.html.haml
.modal#question-share-modal
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title Picture
      .modal-body
        #myCarousel.carousel.slide
          / Carousel items
          .carousel-inner{id: "carousel-inner-#{@picture.id}"}
            - @pictures.each_with_index do |picture, index|
              .item{class: "#{index == 0 ? 'active' : nil}"}
                = image_tag picture.image
                .tag
                  .caption
                    = form_tag tag_pictures_path, :class => 'form-horizontal', :remote => true do
                      = hidden_field_tag 'picture_id', picture.id
                      .form-group
                        .col-md-8
                          = text_field_tag 'tag', '', class: 'form-control', :placeholder => 'Type name of friends or groups', :id => 'tag' + picture.id.to_s
                          = render 'picture',picture:picture
                        .col-md-4
                          = submit_tag 'Tag', class: 'form-control'
                  %strong In picture:
                  %div{:class => "name_list #{picture.id}"}
                    - picture.user_list.each do |p|
                      .btn-group
                        .btn.btn-info
                          = p
                          = link_to raw("<i class=\"glyphicon glyphicon-remove\"></i>"), remove_tag_picture_path(picture, :tag => p), :method => :post, :remote => true
                  / render for custom js and css
                  / = render "picture"

          / Carousel nav
          %a.left.carousel-control{'data-slide' => 'prev', :href => '#myCarousel'}
            %span.glyphicon.glyphicon-chevron-left
          %a.right.carousel-control{'data-slide' => 'prev', :href => '#myCarousel'}
            %span.glyphicon.glyphicon-chevron-right
      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button', id: 'close'} Close

app/views/pictures/edit.html.haml
%h1 Editing picture

= render 'form'

= link_to 'Show', @picture
\|
= link_to 'Back', pictures_path

app/views/pictures/index.html.haml
%h1 Listing pictures

%table
  %tr
    %th Title
    %th Image
    %th Imageable
    %th Imageable type
    %th
    %th
    %th

  - @pictures.each do |picture|
    %tr
      %td= picture.title
      %td= picture.image
      %td= picture.imageable_id
      %td= picture.imageable_type
      %td= link_to 'Show', picture
      %td= link_to 'Edit', edit_picture_path(picture)
      %td= link_to 'Destroy', picture, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Picture', new_picture_path

app/views/pictures/new.html.haml
%h1 New picture

= render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @picture.title
%p
  %b Image:
  = @picture.image
%p
  %b Imageable:
  = @picture.imageable_id
%p
  %b Imageable type:
  = @picture.imageable_type

= link_to 'Edit', edit_picture_path(@picture)
\|
= link_to 'Back', pictures_path

app/views/pictures/show.js.erb
$('.modal').modal('hide');
$('#primary-modal').html('<%= j(render('pictures/show')) %>');
$('#question-share-modal').modal('show');